### ISSUE TITLE
Hospendando um blog na AWS

### ISSUE THREAD

**Issue by robsonbittencourt** [frontendbr/poste-mais#50]
Estou escrevendo um post (na verdade o primeiro do blog) demonstrando passo a passo como hospedar um blog estático na AWS com um custo muito baixo.

Se alguém tiver sugestões, serão bem vindas.

---
### Pauta publicada
- [Hospendando seu Blog Na AWS por Centavos](http://rbittencourt.com/hospedando-seu-blog-na-aws-por-centavos/) por @robsonbittencourt

**Comment by douglascamata** [comment]
Vai explicar como hospedar em um bucket do S3, certo? Se sim, acho interessante mostrar como usar o CloudFront (cdn) junto com o S3 para servir os arquivos.

**Comment by robsonbittencourt** [comment]
Sim essa é a ideia @douglascamata :+1: 
Vou mostrar também o Route53 como alternativa de domínio.

**Comment by robsonbittencourt** [comment]
Demorou mais saiu. Primeiro post do blog :laughing: Qualquer feedback é bem vindo.

http://rbittencourt.com/hospedando-seu-blog-na-aws-por-centavos/

**Comment by fricks** [comment]
Achei confuso.

**Comment by douglascamata** [comment]
Pessoalmente, eu achei bem tranquilo, porque já estou familiarizado com os serviços da Amazon. Talvez esse seja o ponto que causa confusão. Você já os conhecia, @fricks?

**Comment by robsonbittencourt** [comment]
@fricks quais pontos você achou confuso. Talvez tenha ficado mesmo, como foi meu primeiro post. Por isso é importante o seu feedback para que no próximo eu possa melhorar.

**Comment by fricks** [comment]
@douglascamata eu não conhecia e por esse motivo eu acho que ficou confuso.
@robsonbittencourt talvez dar mais detalhes dos passos, eu acho que você escreveu o post para alguem que já conhece sobre o assunto que não é meu caso.

**Comment by douglascamata** [comment]
@robsonbittencourt você já tem mais assunto pra 3 posts então: S3, CloudFront e Route52, ou AWS em geral.

**Comment by robsonbittencourt** [comment]
@fricks entendi, vou tentar melhorar nos próximos. Valeu pelo feedback.
@douglascamata com certeza!!
