### ISSUE TITLE
Javascript Tests

### ISSUE THREAD

**Issue by bukinoshita** [frontendbr/poste-mais#62]
Introdução de testes tanto pra JavaScript + AngularJS usando Jasmine.

Eu vi que tem os do @fdaciuk, mas seria legal ver testes reais também ao invés de dumb test (  1 + 3 = 4), saca? Se alguém puder dar um salve nesse assunto ...

**Comment by fdaciuk** [comment]
Acho válido @BuKinoshita! Não sei quando vou conseguir escrever novamente, possivelmente em breve. Se alguém conseguir fazer seria bem da hora :)

Vou tentar escrever sobre alguns katas com exemplos mais da "vida real", pra dar mais noção de como fazer testes em projetos reais :)

**Comment by BuKinoshita** [comment]
:+1: 

Tem um post que fala de Test para AngularJS que achei esses dias, muito bom.
http://www.yearofmoo.com/2013/01/full-spectrum-testing-with-angularjs-and-karma.html
