### ISSUE TITLE
[Geral] Compartilhe seu conhecimento

### ISSUE THREAD

**Issue by raphaelfabeni** [frontendbr/poste-mais#9]
Tive essa conversa recentemente com uns amigos, e comentamos disso que muitas vezes, **várias** pessoas deixam de escrever, compartilhar, postar e por aí vai pelo simples fato de achar que determinado assunto é _muito simples_ ou com receio do que as pessoas irão pensar.

---
### Pauta publicada
- [Compartilhe seu conhecimento](http://www.raphaelfabeni.com.br/compartilhe-conhecimento/) por @raphaelfabeni

**Comment by hugobessaa** [comment]
E também porque alguém já postou sobre o assunto. Todos os posts são bem-vindos!

**Comment by fdaciuk** [comment]
Exato! Conteúdo nunca é demais! E cada um tem uma forma muito particular de escrever, então nunca terão dois posts iguais (a não ser que alguém copie mesmo haha :P)!

:dancer: :dancer:

**Comment by LFeh** [comment]
Bom tema heim...

**Comment by felquis** [comment]
Vou blogar sobre isso, compartilhando minha experiência com blogs que tem 4 anos já, [esse é meu primeiro post](http://tutsmais.com.br/blog/html/atributos-dir-e-lang/), mas não é pra fechar a isso, acho que essa issue é uma troca de experiência necessária entre os aspirantes a blogueiros e contribuidores.

**Comment by felquis** [comment]
Alias, minha experiência de blogueiro tem 4 anos e 2 dias.

**Comment by raphaelfabeni** [comment]
Tenho um rascunho que tinha começado a escrever um tempo atrás. Vou retomar.

**Comment by nandomoreiraweb** [comment]
seguindo...

**Comment by DaniloAgostinho** [comment]
Meu problema até então era a insegurança, medo de vocês mais experientes não gostarem, repudiarem haha.

acredito que estou prejudicando a web, meu conhecimento só tenho compartilhado em sala de aula. 

mais isso esta mudando, meu desejo mudou, estou com sede de compartilhar conhecimento - acho que é a comunidade que esta despertando isso em mim.

;)

**Comment by hugobessaa** [comment]
Que ótimo que está começando a pensar assim! Quanto mais conteúdo criado por pessoas com vontade de ensinar de verdade, melhor. Não importa se são coisas básicas, intermediárias ou avançadas.

Sabe o que eu já vi muito acontecer? Alguém mais novo na área conseguir explicar algum assunto de uma forma muito mais simples do que alguém com mais tempo.

**Comment by DaniloAgostinho** [comment]
pois eh, acho que isso acontece porque agente mais iniciante tem uma pega básica da coisa, e dai quem já é avançado perde a pegada básica ou não consegue mais falar nossa língua. 

sei lá hahah

aprender é legal e ensinar melhor ainda! :)

**Comment by raphaelfabeni** [comment]
Fala @DaniloAgostinho ! Bacana você citar isso. Insegurança acredito eu todos tem. Uns lidam melhor com ela do que outros. De qualquer forma, manda bala cara. Eu tenho na cabeça que **nada** é irrelevante, e algo que muitas vezes pode ser simples pra você, pode salvar a dúvida de uma outra pessoa.

**Comment by jorgekury** [comment]
Opa @DaniloAgostinho, ano passado eu tava com esse pensamento, receio do que escrever, ou como escrever, porem esse ano tracei uma meta de compartilhar o meu conhecimento, cara é incrível como você pode ajudar pessoas com o pouco ou muito que você sabe. por que as vezes você faz tanto algo que pra você parece simples, mas pra quem ta começando é uma baita ajuda que você ta oferecendo.

**Comment by DaniloAgostinho** [comment]
@raphaelfabeni é isso ai irmão, já faz alguns dias que estou criando meu blog, tenho boas ideias pra ele. rs. 

estou pretendendo escrever sobre minha vida, minhas experiência. 

este repo esta me ajudando bastante.

**Comment by DaniloAgostinho** [comment]
@jorgekury que meta massa velho! vou seguir essa mesma pegada. =D

**Comment by raphaelfabeni** [comment]
Demorou mas saiu! =)
http://www.raphaelfabeni.com.br/compartilhe-conhecimento/

**Comment by DaniloAgostinho** [comment]
@raphaelfabeni massa seu post!

**Comment by sergiokopplin** [comment]
:+1:
