### ISSUE TITLE
[Flutter]Como trabalhar com rotas para outros arquivos | Concluído

### ISSUE THREAD

**Issue by rodriguesJeff** [frontendbr/poste-mais#91]
É de suma importância que saibamos como trabalhar com rotas em qualqer framework que venhamos a utilizar, a ideia desse artigo é socorrer as pessoas que assim como eu sofreram para aprender a usar rotas no Flutter.

**Comment by rodriguesJeff** [comment]
Concluída
https://medium.com/flutter-comunidade-br/roteamento-simples-com-flutter-7b18813037d2

**Comment by felipefialho** [comment]
Parabéns @rodriguesJeff

**Comment by rodriguesJeff** [comment]
Valeu cara, se possível só da uma editada aí que não é JS, é Dart
Blz?
